#!/usr/bin/env bash
#
# Bump the Homebrew tap formula to the current VERSION — the two-line edit
# (url, sha256) done automatically instead of by hand. Only needs the git tag
# to exist on the mcp-runtime repo; it does not depend on the binary release
# workflow or its approval gate, since the formula builds from GitHub's
# autogenerated source tarball for the tag, not our built artifacts.
#
# Usage: scripts/update-tap-formula.sh [tag]
#   tag defaults to v<VERSION>. The tag must already be pushed to origin.
set -euo pipefail

tap_repo="maelys-dev/homebrew-tap"
tap_url="https://github.com/${tap_repo}.git"
mcp_repo="maelys-dev/mcp-runtime"
root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$root"

tag="${1:-v$(cat VERSION)}"
version="${tag#v}"
archive_url="https://github.com/${mcp_repo}/archive/refs/tags/${tag}.tar.gz"

if ! git ls-remote --exit-code --tags "https://github.com/${mcp_repo}.git" "$tag" >/dev/null 2>&1; then
  echo "error: tag $tag is not on origin yet — push it before updating the tap" >&2
  exit 1
fi

# codeload.github.com is occasionally rate-limited or degraded; retry with backoff
# rather than fail on the first transient error.
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
archive="$tmp/src.tar.gz"
attempt=1
until curl -fsSL -o "$archive" "$archive_url"; do
  if [ "$attempt" -ge 5 ]; then
    echo "error: failed to download $archive_url after $attempt attempts" >&2
    echo "check https://www.githubstatus.com before retrying" >&2
    exit 1
  fi
  sleep $((attempt * 10))
  attempt=$((attempt + 1))
done
sha256="$(shasum -a 256 "$archive" | cut -d' ' -f1)"

echo "==> $tag: $sha256"

tap_dir="$tmp/tap"
git clone -q "$tap_url" "$tap_dir"
formula="$tap_dir/Formula/mcp-runtime.rb"
[ -f "$formula" ] || { echo "error: $formula not found" >&2; exit 1; }

# Rewrite exactly the url and sha256 lines; fail if either pattern is absent
# rather than silently leaving the formula unchanged.
python3 - "$formula" "$archive_url" "$sha256" <<'PY'
import re, sys
path, url, sha = sys.argv[1:4]
text = open(path).read()
new_text, n_url = re.subn(r'^(\s*url) ".*"$', rf'\1 "{url}"', text, count=1, flags=re.M)
if n_url != 1:
    sys.exit(f"error: could not find a single url line in {path}")
new_text, n_sha = re.subn(r'^(\s*sha256) ".*"$', rf'\1 "{sha}"', new_text, count=1, flags=re.M)
if n_sha != 1:
    sys.exit(f"error: could not find a single sha256 line in {path}")
open(path, 'w').write(new_text)
PY

if command -v brew >/dev/null 2>&1; then
  brew style "$formula" || echo "warning: brew style reported issues (continuing)" >&2
fi

if git -C "$tap_dir" diff --quiet; then
  echo "==> tap formula already at $tag ($sha256); nothing to push"
  exit 0
fi

git -C "$tap_dir" -c user.name=davidb987654 -c user.email=davidb987654@users.noreply.github.com \
  commit -q -am "Bump mcp-runtime to ${version}"
git -C "$tap_dir" push -q origin main
echo "==> pushed: brew install ${tap_repo##*/}/mcp-runtime now serves ${version}"
